"""auto_migration_20260407_103909

Revision ID: cae3570d55fb
Revises: 
Create Date: 2026-04-07 03:39:10.504868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae3570d55fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_books_author', 'books', ['author'], unique=False)
    op.create_index('idx_books_author_created', 'books', ['author', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_books_created_at', 'books', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index('idx_books_created_at', table_name='books', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_books_author_created', table_name='books', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_books_author', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
